package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// HookType represents the type of shell hook
type HookType string

const (
	HookBash HookType = "bash"
	HookZsh  HookType = "zsh"
)

// HookConfig contains hook configuration
type HookConfig struct {
	ShellType HookType
	CacheDir  string
	BinPath   string
}

// GenerateHookScript generates shell integration script
func GenerateHookScript(config HookConfig) (string, error) {
	var script strings.Builder

	switch config.ShellType {
	case HookBash, HookZsh:
		script.WriteString("# md-over-here hook integration\n")
		script.WriteString("# Generated by md-over-here hook init\n")
		script.WriteString("\n")

		// Function to get cache stats
		fmt.Fprintf(&script, "_mdoh_prompt() {\n")
		fmt.Fprintf(&script, "  local cache_dir=\"%s\"\n", config.CacheDir)
		fmt.Fprintf(&script, "  local count=0\n")
		fmt.Fprintf(&script, "  if [ -d \"$cache_dir\" ]; then\n")
		fmt.Fprintf(&script, "    count=$(find \"$cache_dir\" -type f 2>/dev/null | wc -l)\n")
		fmt.Fprintf(&script, "  fi\n")
		fmt.Fprintf(&script, "  local bin=\"%s\"\n", config.BinPath)
		fmt.Fprintf(&script, "  if [ \"$count\" -gt 0 ]; then\n")
		fmt.Fprintf(&script, "    echo \"md-over-here: $count cached\"\n")
		fmt.Fprintf(&script, "  fi\n")
		fmt.Fprintf(&script, "}\n")

		// Add to PROMPT_COMMAND (bash) or precmd (zsh)
		if config.ShellType == HookBash {
			fmt.Fprintf(&script, "if [[ -z \"$PROMPT_COMMAND\" ]]; then\n")
			fmt.Fprintf(&script, "  PROMPT_COMMAND=\"_mdoh_prompt\"\n")
			fmt.Fprintf(&script, "else\n")
			fmt.Fprintf(&script, "  PROMPT_COMMAND=\"_mdoh_prompt;$PROMPT_COMMAND\"\n")
			fmt.Fprintf(&script, "fi\n")
		} else {
			fmt.Fprintf(&script, "typeset -ag precmd\n")
			fmt.Fprintf(&script, "precmd() {\n")
			fmt.Fprintf(&script, "  _mdoh_prompt\n")
			fmt.Fprintf(&script, "}\n")
		}

	default:
		return "", fmt.Errorf("unsupported shell type: %s", config.ShellType)
	}

	return script.String(), nil
}

// GetShellScriptPath returns the path to install hooks
func GetShellScriptPath(shellType HookType) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("getting home directory: %w", err)
	}

	var scriptPath string
	switch shellType {
	case HookBash:
		scriptPath = filepath.Join(home, ".bashrc")
	case HookZsh:
		scriptPath = filepath.Join(home, ".zshrc")
	default:
		return "", fmt.Errorf("unsupported shell type: %s", shellType)
	}

	return scriptPath, nil
}

// DetectShell detects the current shell
func DetectShell() HookType {
	shell := os.Getenv("SHELL")
	if strings.Contains(shell, "zsh") {
		return HookZsh
	}
	return HookBash // Default to bash
}
